pages:
  stage: deploy
  script:
    - mkdir -p .public
    - cp -r * .public
  artifacts:
    paths:
      - public
  only:
    - main

pages-beta:
  extends: pages
  stage: deploy
  script:
    - mkdir -p .public/beta
    - cp -r * .public/beta
  artifacts:
    paths:
      - public
  only:
    - dev

pages-final:
  extends: pages
  stage: deploy
  script:
    - mv .public public
  artifacts:
    paths:
      - public