pages:
  stage: deploy
  script:
    - mkdir -p .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main

pages-beta:
  extends: pages
  stage: deploy
  script:
    - mkdir .beta
    - mkdir public
    - cp -r * .beta
    - mv .beta public/beta
  artifacts:
    paths:
      - public/beta
  only:
    - dev