build-main:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - mkdir -p .public
    - cp -R * .public
    - git clone --depth=1 --branch=dev $CI_REPOSITORY_URL
    - mv woah-its-rex .public/dev
    - git clone --depth=1 --branch=beta $CI_REPOSITORY_URL
    - mv woah-its-rex .public/beta
  artifacts:
    paths:
      - .public

build-beta:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "beta"
  script:
    - git clone --depth=1 --branch=main $CI_REPOSITORY_URL
    - mv woah-its-rex .public
    - git clone --depth=1 --branch=dev $CI_REPOSITORY_URL
    - mv woah-its-rex .public/dev
    - mkdir -p .public/beta
    - cp -R * .public/beta
  artifacts:
    paths:
      - .public

build-dev:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
    - git clone --depth=1 --branch=main $CI_REPOSITORY_URL
    - mv woah-its-rex .public
    - git clone --depth=1 --branch=beta $CI_REPOSITORY_URL
    - mv woah-its-rex .public/beta
    - mkdir -p .public/dev
    - cp -R * .public/dev
  artifacts:
    paths:
      - .public

pages:
  stage: deploy
  script:
    - rm -rf .public/.*
    - mv .public public
  artifacts:
    paths:
      - public
  dependencies:
    - build-main
    - build-beta
    - build-dev